export interface CompanyDetail {
    Company: CompanyModel;
}

export interface CompanyModel {
    FirstName: string;
    MiddleName: string;
    LastName: string;
    Username: string;
    Password: string;
    ConfirmPassword: string;
    Pin: string;
    SaltHash: string;
    CompCode: number;
    CompName: string;
    Code: string;
    CompanyAzurePath: string;
    URL: string;
    Phone: string;
    AlternateMobile: string;
    Email: string;
    BankName: string;
    BankAccountNo: string;
    BankIFSCCode: string;
    BillAuthorisedCondition: string;
    BillTermsCondition: string;
    BusinessTypeId: number;
    FirmTypeId: number;
    CountryId: number | null;
    StateCode: string;
    City: string;
    PinCode: string;
    Website: string;
    Facebook: string;
    Skype: string;
    Twitter: string;
    LinkedIn: string;
    PAN: string;
    TAN: string;
    CIN: string;
    GST_TIN: string;
    FSSAI_LIC_No: string;
    EstablishmentCode: string;
    ESINo: string;
    PFNo: string;
    AuthorizedPerson: string;
    IECCode: string;
    EWayUsername: string;
    EWayPassword: string;
    GSTNUsername: string;
    VATGSTStatusId: number | null;
    MarketPlaceUrl: string;
    Description: string;
    Remark: string;
    CompLogo: string;
    InvoiceHeaderColor: string;
    CompLogoBase64Image: string;
    PrintName: string;
    ShortName: string;
    Address: string;
    PrintAddress: string;
    DrugLicenceNo: string;
    OtherLicence1Caption: string;
    OtherLicence1No: string;
    OtherLicence2Caption: string;
    OtherLicence2No: string;
    IsActive: boolean;
    CreatedBy: number;
    CreatedOn: string;
    EditedBy: number | null;
    EditedOn: string | null;
    SuperAdminId: number | null;
    IdleTimeOut: number | null;
    UserReferCode: string;
    ReferalReferCode: string;
    ReferredByUserId: number | null;
    ReferredRoleId: number | null;
    RegisteredOTP: string;
    RequestId: string;
}